// Runtime bundle: side-effect imports in the exact original CORE_SCRIPTS load order.
// Phase 4: sprintf, gaussBlur, mathUtils, colormaps, browserCompat are now proper ES
// module exports; they are imported directly by viewer.ts and other consumers.
// The remaining @ts-nocheck modules still use side-effect registration on globalThis.
import './core/colorUtils'
import './core/imageFilters'
import './core/regSelect'
import './core/inlineAssets'
import './core/domAdapter'
import './core/basicUtils'
import './core/fitsRuntime'
import './core/fitsBootstrap'
import './core/viewerUtils'
import './core/viewerEvents'
import './core/viewerPlugins'
import './core/commands'
import './core/helperRuntime'
import './core/shapeEngine'
import './core/nativeShapeEngine'
import './core/initAnalysis'
import './core/publicApi'
import './core/viewerInit'
import './core/viewerDisplay'
import './core/viewerImageCore'
import './core/viewerImageRender'
import './core/viewerImageCoords'
import './core/viewerImageData'
import './core/viewerRegions'
import './core/viewerOverlays'
import './viewer'
